### ISSUE TITLE
Escaping '\' not needed & missing whitespace escaping in 'FieldTextValue'

### ISSUE THREAD

**Issue by R-Studio** [markwragg/PowerShell-Influx#32]
Hi 
I forked your really cool project and noticed following in your private PowerShell-function "**Influx/Private/Out-InfluxEscapeString.ps1**":
- Escaping of '\' is not needed ([InfluxLine protocol docs](https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_tutorial/#special-characters-and-keywords): _line protocol does not require users to escape the backslash character \ but will not complai_)
- Missing whitespace escaping in 'FieldTextValue'

your code in "Influx/Private/Out-InfluxEscapeString.ps1":
```
"Measurement" { $String -Replace '(\s|,|\\)', '\$1' }
"FieldTextValue" { $String -Replace '("|\\)', '\$1' }
"Other" { $String -Replace '(\s|=|,|\\|")', '\$1' }
default { $String -Replace '(\s|=|,|\\|")', '\$1' }
```

my changes in "Influx/Private/Out-InfluxEscapeString.ps1":
```
"Measurement" { $String -Replace '(\s|,)', '\$1' }
"FieldTextValue" { $String -Replace '(\s|")', '\$1' }
"Other" { $String -Replace '(\s|=|,|")', '\$1' }
default { $String -Replace '(\s|=|,|")', '\$1' }
```
-> More informations about the [changes](https://github.com/R-Studio/PSInfluxLineConverter/commit/8903adfcc61816a15746a58ad249bcc3d3271857).

_PS: Excuse me for not making an pull request, but nevertheless I hope it helps._

**Comment by Trovalo** [comment]
Hi and thanks for the interest, but I think the code is right as it is now.

About the whitespace (" ") in field values:
From the [line protocol tutorial](https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_tutorial/#special-characters-and-keywords)
> For string field values use a backslash character \ to escape:
> - double quotes "

Every other char does not need escaping, therefore nothing more is needed

About the escaped backslash ("\\")
It is the escape char itself, even if the line protocol _will not complain_ the reason is simple, what if in your data you actually contain a double backslash "\\\\" (ie: an URL or network path).
By not escaping both chars one of them will be lost as it will get interpreted as an escape sequence)

@R-Studio If you have any issue with the output of the function I will be glad to reproduce and fix it

**Comment by R-Studio** [comment]
Hi Trovalo, thanks for your reply.

I think you're right. Because I used a part of the PowerShell modul in relation to the Telegraf Agent. 
So maybe the backslashes and whitespaces are handled by Telegraf.
